import { HttpService } from '@nestjs/axios';
import { CustomersService } from '../customers/customers.service';
import { StoresService } from '../stores/stores.service';
import { ServicesService } from '../services/services.service';
import { EmployeesService } from '../employees/employees.service';
import { AppointmentsService } from '../appointments/appointments.service';
import { OrdersService } from '../orders/orders.service';
export declare class AiAssistantService {
    private readonly httpService;
    private readonly customerService;
    private readonly storeService;
    private readonly serviceService;
    private readonly employeeService;
    private readonly appointmentService;
    private readonly orderService;
    private conversationHistory;
    private appointmentInfo;
    private readonly maxHistoryLength;
    constructor(httpService: HttpService, customerService: CustomersService, storeService: StoresService, serviceService: ServicesService, employeeService: EmployeesService, appointmentService: AppointmentsService, orderService: OrdersService);
    chat(userId: number, message: string, context?: any): Promise<any>;
    private getNextQuestion;
    private extractAppointmentInfo;
    private handleSystemQuery;
    private handleUnrelatedQuestion;
    private simpleExtractInfo;
    private generateGuidance;
    private defaultGuidance;
    private getSimpleGuidance;
    private requestConfirmation;
    private findAvailableEmployee;
    private createAppointment;
    private hasAllAppointmentInfo;
    private getMissingInfo;
    private isConfirmation;
    private isCancellation;
    private isRandomAssign;
    private resolveEmployeeId;
    private checkTimeConflict;
    private getConversationHistory;
    clearHistory(userId: number): void;
    processVoice(audioUrl: string, userId: number): Promise<any>;
    generateRecommendation(userId: number, context: any): Promise<any>;
}
